zenko-zookeeper:

kafka:
  persistentVolume:
    enabled: true

s3-data:
  persistentVolume:
    enabled: true
    accessModes:
    - ReadWriteOnce

s3-metadata:
  persistentVolume:
    enabled: true
